name: ESLint
on:
  push:
    paths:
      - 'src/**.ts'
      - 'src/**.test'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Ensure package.json is present
        run: |
          if [ ! -f "package.json" ]; then
            echo "Error: package.json not found."
            exit 1
          fi

      - name: Print package.json content
        run: cat package.json

      - name: Set up Node version
        uses: actions/setup-node@v4
        with:
          node-version: 16
          check-latest: true
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
