name: ESLint
on:
  push:
    paths:
      - 'src/**.ts'
      - 'src/**.test'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Set up Node version
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
