name: ESLint
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Set up Node version
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 'current'
          check-latest: true
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run eslint . --ext .ts
