name: Test
on:
  push:
    paths:
      - 'src/tests/**.test.ts'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x', '20.x', 'latest']
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set up Node version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm run test
