name: Unit test with Jest
on:
  push:
    paths:
      - 'src/**.test.ts'
  pull_request:
    paths:
        - 'src/**.test.ts'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set up Node version
        uses: actions/setup-node@v4
        with:
          node-version: 16
          check-latest: true
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
      - name: Run Jest test
        run: npm run test
